### ISSUE TITLE
Wrong power connection on Ultrasonic sensor

### ISSUE THREAD

**Issue by jadonk** [beagleboard/cloud9-examples#15]
Hey @MarkAYoder 

https://github.com/beagleboard/cloud9-examples/blob/master/sensors/images/ultrasonic.png

I think this sensor should be powered by 3.3V, not 5V.. ....and certainly not the VDD_5V

**Comment by MarkAYoder** [comment]
Odd.  My sensor has +5V labeled on it, but it appears to work fine with 3.3v.
When we did this in the cookbook there wasn't a voltage divider, so I left it off here too.
It has to get some rather long distances before it's over 1.8V.
