### ISSUE TITLE
Corrupt JPEG data warning while running TIDL examples

### ISSUE THREAD

**Issue by vlasov01** [beagleboard/cloud9-examples#19]
Hi,

I'm exploring video stream processing capabilities of BBAI.
I was able build and run TIDL examples on BBAI. But I'm getting a constant stream of warnings in the terminal window: 
`Corrupt JPEG data: 1 extraneous bytes before marker 0xd9`

Regards,

Sergey

**Comment by jadonk** [comment]
Can you run 'sudo apt update; sudo apt upgrade' and see if this is still the case? I believe the fix is in the repository now.

https://github.com/rcn-ee/repos/commit/6e64b6272377994562e4a6f4a0d7b9f7f1a74fc9#diff-5b2cf38c392fbbdfaa45e100ee0ed62a
