### ISSUE TITLE
problem with make

### ISSUE THREAD

**Issue by fforoutan** [beagleboard/cloud9-examples#26]
when I Want make blinkInternalLED.pru1_1.c in /var/lib/cloud9/BeagleBone/AI/pru directory I get this Message:
`root@beaglebone:/var/lib/cloud9/BeagleBone/AI/pru# source setup.sh
TARGET=blinkInternalLED.pru1_1
root@beaglebone:/var/lib/cloud9/BeagleBone/AI/pru# make
/var/lib/cloud9/common/Makefile:28: MODEL=BeagleBoard.org_BeagleBone_AI,TARGET=blinkInternalLED.pru1_1,COMMON=/var/lib/cloud9/common
/var/lib/cloud9/common/Makefile:147: GEN_DIR=/tmp/cloud9-examples,CHIP=am57xx,PROC=pru,PRUN=1_1,PRU_DIR=/sys/class/remoteproc/remoteproc1,EXE=.out
-    Stopping PRU 1_1
CC      blinkInternalLED.pru1_1.c
"/var/lib/cloud9/common/prugpio.h", line 4: warning #1181-D: #warning directive: "Found AI"
"blinkInternalLED.pru1_1.c", line 36: warning #112-D: statement is unreachable
LD      /tmp/cloud9-examples/blinkInternalLED.pru1_1.o
error: cannot find file "/usr/share/ti/starterware/pru/libdrivers.a"
error: errors encountered during linking;
   "/tmp/cloud9-examples/blinkInternalLED.pru1_1.out" not built
/var/lib/cloud9/common/Makefile:196: recipe for target '/tmp/cloud9-examples/blinkInternalLED.pru1_1.out' failed
make: *** [/tmp/cloud9-examples/blinkInternalLED.pru1_1.out] Error 1
rm /tmp/cloud9-examples/blinkInternalLED.pru1_1.o`

**Comment by jadonk** [comment]
https://github.com/beagleboard/cloud9-examples/commit/4cbed7f391e53de12d303a97d68b639229db0a5e

**Comment by jadonk** [comment]
Oh, guess this was actually fixed with 5bacbcd2e8079f6e8afd8bb0969b9e221fdff80e
