### ISSUE TITLE
Sample classification.tidl.cpp did not work

### ISSUE THREAD

**Issue by donmast** [beagleboard/cloud9-examples#28]
I just started working on Beaglebone AI board two days ago, 3/24/2020, installed the latest OS image, update and upgrades were performed for everything. When I ran the classification program. This is what I got:
Started /var/lib/cloud9/: classification.tidl.cpp
File path: /var/lib/cloud9/BeagleBone/AI/tidl
File: /var/lib/cloud9/BeagleBone/AI/tidl/classification.tidl.cpp
Arguments: 
File name: classification.tidl.cpp
File extension: cpp
File base name: classification.tidl
Packages: ~.c9/packages
Project path: /var/lib/cloud9/
Project name: projectname
Hostname: localhost
Hostname path: https://undefined/BeagleBone/AI/tidl/classification.tidl.cpp
URL: http://localhost
Port: 8080
IP: 0.0.0.0
Command: BeagleBone/AI/tidl/classification.tidl.cpp
Python: python3
Python path: /usr/lib/python3.7/dist-packages:/usr/local/lib/python3.7/dist-packages
/var/lib/cloud9/common/Makefile:28: MODEL=BeagleBoard.org_BeagleBone_AI,TARGET=classification.tidl,COMMON=/var/lib/cloud9/common
/var/lib/cloud9/common/Makefile:147: GEN_DIR=/tmp/cloud9-examples,CHIP=am57xx,PROC=tidl,PRUN=,PRU_DIR=,EXE=.so
ti-mct-heap-check -c
sudo mjpg_streamer -i "input_opencv.so -r 640x480 --filter ./classification.tidl.so" -o "output_http.so -p 8080 -w /usr/share/mjpg-streamer/www"
[sudo] password for debian:
MJPG Streamer Version.: 2.0
 i: device........... : default
 i: Desired Resolution: 640 x 480
Unable to stop the stream: Invalid argument
 i: VideoCapture::open() failed
/var/lib/cloud9/common/Makefile:169: recipe for target 'start' failed
make: *** [start] Error 1

Process exited with code: 2

**Comment by jomoengineer** [comment]
Looking at the TIDL Makefile, it calls out "input_opencv.so" but my camera is listed as a "uvcvideo". Should this use "input_uvc.so" and add "-d /dev/video1"?

This is what I see when unplugging and plugging my camera:
```
Nov  3 10:28:25 beaglebone kernel: [  711.750750] usb 1-1: USB disconnect, device number 2
Nov  3 10:28:28 beaglebone kernel: [  714.306543] usb 1-1: new high-speed USB device number 3 using xhci-hcd
Nov  3 10:28:30 beaglebone kernel: [  716.696680] usb 1-1: New USB device found, idVendor=046d, idProduct=082d
Nov  3 10:28:30 beaglebone kernel: [  716.696713] usb 1-1: New USB device strings: Mfr=0, Product=2, SerialNumber=1
Nov  3 10:28:30 beaglebone kernel: [  716.696735] usb 1-1: Product: HD Pro Webcam C920
Nov  3 10:28:30 beaglebone kernel: [  716.696755] usb 1-1: SerialNumber: C0DB0F6F
Nov  3 10:28:30 beaglebone kernel: [  716.703560] uvcvideo: Found UVC 1.00 device HD Pro Webcam C920 (046d:082d)
Nov  3 10:28:30 beaglebone kernel: [  716.709168] uvcvideo 1-1:1.0: Entity type for entity Processing 3 was not initialized!
Nov  3 10:28:30 beaglebone kernel: [  716.709201] uvcvideo 1-1:1.0: Entity type for entity Extension 6 was not initialized!
Nov  3 10:28:30 beaglebone kernel: [  716.709230] uvcvideo 1-1:1.0: Entity type for entity Extension 12 was not initialized!
Nov  3 10:28:30 beaglebone kernel: [  716.709289] uvcvideo 1-1:1.0: Entity type for entity Camera 1 was not initialized!
Nov  3 10:28:30 beaglebone kernel: [  716.709336] uvcvideo 1-1:1.0: Entity type for entity Extension 8 was not initialized!
Nov  3 10:28:30 beaglebone kernel: [  716.709368] uvcvideo 1-1:1.0: Entity type for entity Extension 9 was not initialized!
Nov  3 10:28:30 beaglebone kernel: [  716.709393] uvcvideo 1-1:1.0: Entity type for entity Extension 10 was not initialized!
Nov  3 10:28:30 beaglebone kernel: [  716.709418] uvcvideo 1-1:1.0: Entity type for entity Extension 11 was not initialized!
Nov  3 10:28:30 beaglebone kernel: [  716.713223] input: HD Pro Webcam C920 as /devices/platform/44000000.ocp/488c0000.omap_dwc3_2/488d0000.usb/xhci-hcd.1.auto/usb1/1-1/1-1:1.0/input/input3
Nov  3 10:28:31 beaglebone mtp-probe: checking bus 1, device 3: "/sys/devices/platform/44000000.ocp/488c0000.omap_dwc3_2/488d0000.usb/xhci-hcd.1.auto/usb1/1-1"
Nov  3 10:28:31 beaglebone mtp-probe: bus: 1, device: 3 was not an MTP device

```

**Comment by donmast** [comment]
Thank you for the inputs.
This program uses opencv VideoCapture class with open() method VideoCaptuer::video().
I believe VideoCapture class can handle the USB UVC cameras. Also /dev/video1 is specified in main.cpp as input_line = 1; I think.

**Comment by jomoengineer** [comment]
Actually setting '-d /dev/video1' in the common Makefile seemed to do the trick.  I now have video from the camera in the TIDL example. 

This is what I changed at line 179 in the Makefile at:
**/var/lib/cloud9/common$**

```
else ifeq ($(PROC),tidl)
        ti-mct-heap-check -c
        sudo mjpg_streamer -i "input_opencv.so -d /dev/video1 -r 640x480 --filter ./$(TARGET)$(EXE)" -o "output_http.so -p 8080 -w /usr/share/mjpg-streamer/www"
else

```

**Comment by donmast** [comment]
Good tip. Will try that.
Thank you my friend.

**Comment by donmast** [comment]
That did the trick!  Appreciate your help.
